<?php

namespace App\Filament\Resources\Settings;

use App\Filament\Resources\Settings\CurrencyResource\Pages;
use App\Filament\Resources\Settings\CurrencyResource\RelationManagers;
use App\Models\Settings\Currency;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class CurrencyResource extends Resource
{
    use \App\HasConfigurations;

    protected static ?string $model = Currency::class;
    protected static ?int $navigationSort = 8;


    public static function canDelete(Model $record): bool
    {
        if($record->id ==1){
            return false;
        }
        return parent::canDelete($record); // TODO: Change the autogenerated stub
    }
    public static function canEdit(Model $record): bool
    {
        if($record->id ==1){
            return false;
        }
        return parent::canEdit($record); // TODO: Change the autogenerated stub
    }
    protected static ?string $navigationIcon = 'ri-currency-line';
    protected static ?string $label = "دراو";
    protected static ?string $pluralLabel = "دراوەکان";
    protected static ?string $navigationGroup = 'ڕێکخستنەکان';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->label('ناو')
                    ->maxLength(255),
                Forms\Components\TextInput::make('symbol')
                    ->required()
                    ->label('هێما')
                    ->maxLength(255),
                Forms\Components\TextInput::make('rate')
                    ->required()
                    ->label('نرخ')
                    ->numeric(),
                Forms\Components\TextInput::make('decimal_places')
                    ->required()
                    ->label('پۆینتەکان')
                    ->numeric()
                    ->default(2),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('id','desc')
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label('ناو')
                    ->searchable(),
                Tables\Columns\TextColumn::make('symbol')
                    ->label('هێما')
                    ->searchable(),
                Tables\Columns\TextColumn::make('rate')
                    ->numeric()
                    ->label('نرخ')
                    ->sortable(),
                Tables\Columns\TextColumn::make('decimal_places')
                    ->label('پۆینتەکان')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->label('سڕینەوە')
                    ->dateTime('Y-m-d')
                    ->formatStateUsing(fn($state)=>"سڕینەوە: ". $state->format('Y-m-d'))
                    ->color(\Filament\Support\Colors\Color::Red)
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label('دروستکردن')
                    ->dateTime('Y-m-d')
                    ->formatStateUsing(fn($state)=>"دروستکردن: ". $state->format('Y-m-d'))
                    ->color(\Filament\Support\Colors\Color::Green)
                    ->sortable(),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label('نوێکردنەوە')
                    ->dateTime('Y-m-d')
                    ->formatStateUsing(fn($state)=>"نوێکردنەوە : ". $state->format('Y-m-d'))
                    ->color(\Filament\Support\Colors\Color::Amber)
                    ->sortable(),
            ])
            ->filters([
                Tables\Filters\TrashedFilter::make(),
                \Malzariey\FilamentDaterangepickerFilter\Filters\DateRangeFilter::make('created_at')
                    ->label('دروستکردن'),
                \Malzariey\FilamentDaterangepickerFilter\Filters\DateRangeFilter::make('updated_at')
                    ->label('نوێکردنەوە'),
                \Malzariey\FilamentDaterangepickerFilter\Filters\DateRangeFilter::make('deleted_at')
                    ->label('سڕینەوە'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
                Tables\Actions\ForceDeleteAction::make(),
                Tables\Actions\RestoreAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                    Tables\Actions\ForceDeleteBulkAction::make(),
                    Tables\Actions\RestoreBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageCurrencies::route('/'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ]);
    }
}
