<?php

namespace App\Models\HR;

use App\HasCurrency;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class EmployeeActivities extends Model
{
    use HasFactory;
    use SoftDeletes;
    use HasCurrency;
    protected $guarded = [];
protected static function boot()
{
    parent::boot(); // TODO: Change the autogenerated stub
    self::creating(function ($model){
        $model->currency_id = $model->employee->currency_id;
    });
}

    public function employee():BelongsTo
    {
        return $this->belongsTo(Employee::class);
    }

    public static function getTypes():array
    {
        return [
          'punish' =>"سزا",
          "bonus" =>"پاداشت" ,
          "absence"=>"ئامادەنەبوون" ,
          "overtime"=>"کاتی زیادە"  ,
            "advance"=>"مووچەی پێشوەختە",
            'salary'=>"مووچە"
        ];
    }
}
