<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

trait HasConfigurations
{
    public static function getNavigationBadge(): ?string
    {
        return number_format(static::getEloquentQuery()->count()??0,0);
    }
    public static function getActiveNavigationIcon(): ?string
    {
        return 'heroicon-s-check-badge'; // TODO: Change the autogenerated stub
    }
    public static function canForceDelete(Model $record): bool
    {
        return false;
    }
    public static function canRestore(Model $record): bool
    {
        return false;
    }
    public static function canDeleteAny(): bool
    {
        return false;
    }
    public static function canForceDeleteAny(): bool
    {
        return  false;
    }
    public static function canRestoreAny(): bool
    {
        return false;
    }
}
